apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-web
  template:
    metadata:
      labels:
        app: php-web
    spec:
      containers:
      - name: php-web
        image: asif48/php_web:v6
        ports:
        - containerPort: 80
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_USER
          value: sai
        - name: MYSQL_PASSWORD
          value: sai
        - name: MYSQL_ROOT_PASSWORD
          value: sai
      volumes:
      - name: mysql-data
        emptyDir: {}

